name: Web App Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      webapp_directory:
        required: true
        type: string
        description: "Specifies the directory of the Azure Web App."
      webapp_name:
        required: true
        type: string
        description: "Specifies the name of the Azure Web App."
      tenant_id:
        required: true
        type: string
        description: "Specifies the tenant id of the deployment."
      subscription_id:
        required: true
        type: string
        description: "Specifies the subscription id of the deployment."
    secrets:
      CLIENT_ID:
        required: true
        description: "Specifies the client id."

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    name: Web App Deploy
    runs-on: [self-hosted]
    continue-on-error: false
    environment: ${{ inputs.environment }}
    concurrency:
      group: webapp-${{ inputs.webapp_name }}-${{ inputs.environment }}
      cancel-in-progress: false

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      # Setup uv
      - name: Setup uv
        id: uv_setup
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version-file: "pyproject.toml"
          working-directory: ${{ inputs.webapp_directory }}
          enable-cache: true
          cache-suffix: "copilot"

      # Install uv dependencies
      - name: Install uv dependencies
        id: uv_dependencies
        working-directory: ${{ inputs.webapp_directory }}
        run: |
          # Create and activate venv
          uv venv webapp-env
          source webapp-env/bin/activate

          # Sync dependencies
          uv lock
          uv sync --no-dev

          # Remove venv
          rm -rf webapp-env

      # Azure login
      - name: Azure login
        id: azure_login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      # Deploy Web App
      - name: Deploy Web App
        id: webapp_deploy
        uses: Azure/webapps-deploy@02a81bead70021f5284939794bcec79c271ab383  # v3.0.8
        with:
          app-name: ${{ inputs.webapp_name }}
          package: ${{ inputs.webapp_directory }}
          startup-command: "gunicorn --bind 0.0.0.0 --worker-class uvicorn.workers.UvicornWorker --timeout 600 app.main:app"
          # restart: true
