name: Web App Test Template

on:
  workflow_call:
    inputs:
      webapp_directory:
        required: true
        type: string
        description: "Specifies the directory of the Azure Web App."

jobs:
  test:
    name: Web App Test
    runs-on: [ubuntu-latest]
    continue-on-error: false

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Setup uv
      - name: Setup uv
        id: uv_setup
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version-file: "pyproject.toml"
          working-directory: ${{ inputs.webapp_directory }}
          enable-cache: true
          cache-suffix: "copilot"

      # Install uv dependencies
      - name: Install uv dependencies
        id: uv_dependencies
        working-directory: ${{ inputs.webapp_directory }}
        run: |
          # Create and activate venv
          uv venv webapp-env
          source webapp-env/bin/activate

          # Sync dependencies
          uv lock
          uv sync

      # Run Python Tests
      - name: Run Python Tests
        id: uv_test
        working-directory: ${{ inputs.webapp_directory }}
        run: |
          uv run pytest tests/
        env:
          WEBAPP_DIRECTORY: ${{ inputs.webapp_directory }}
