name: Web App Test Template

on:
  workflow_call:
    inputs:
      webapp_directory:
        required: true
        type: string
        description: "Specifies the directory of the Azure Web App."

jobs:
  test:
    name: Web App Test
    runs-on: [ubuntu-latest]
    continue-on-error: false

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Setup uv
      - name: Setup uv
        id: uv_setup
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          version-file: "pyproject.toml"
          working-directory: ${{ inputs.webapp_directory }}
          enable-cache: true
          cache-suffix: "copilot"

      # Install uv dependencies
      - name: Install uv dependencies
        id: uv_dependencies
        working-directory: ${{ inputs.webapp_directory }}
        run: |
          # Create and activate venv
          uv venv webapp-env
          source webapp-env/bin/activate
          
          # Sync dependencies
          uv lock
          uv sync

      # Run Python Tests
      - name: Run Python Tests
        id: uv_test
        working-directory: ${{ inputs.webapp_directory }}
        run: |
          uv run pytest tests/
        env:
          WEBAPP_DIRECTORY: ${{ inputs.webapp_directory }}
