name: Web App Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      webapp_directory:
        required: true
        type: string
        description: "Specifies the directory of the Azure Web App."
      webapp_name:
        required: true
        type: string
        description: "Specifies the name of the Azure Web App."
      tenant_id:
        required: true
        type: string
        description: "Specifies the tenant id of the deployment."
      subscription_id:
        required: true
        type: string
        description: "Specifies the subscription id of the deployment."
    secrets:
      CLIENT_ID:
        required: true
        description: "Specifies the client id."

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    name: Web App Deploy
    runs-on: [self-hosted]
    continue-on-error: false
    environment: ${{ inputs.environment }}
    concurrency:
      group: webapp-${{ inputs.webapp_name }}-${{ inputs.environment }}
      cancel-in-progress: false

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Setup uv
      - name: Setup uv
        id: uv_setup
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          version-file: "pyproject.toml"
          working-directory: ${{ inputs.webapp_directory }}
          enable-cache: true
          cache-suffix: "copilot"

      # Install uv dependencies
      - name: Install uv dependencies
        id: uv_dependencies
        working-directory: ${{ inputs.webapp_directory }}
        run: |
          # Create and activate venv
          uv venv webapp-env
          source webapp-env/bin/activate

          # Sync dependencies
          uv lock
          uv sync --no-dev

          # Remove venv
          rm -rf webapp-env

      # Azure login
      - name: Azure login
        id: azure_login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      # Deploy Web App
      - name: Deploy Web App
        id: webapp_deploy
        uses: Azure/webapps-deploy@657f0700ea5214d56a0400d8ac5e8023c963d25d  # v3.0.6
        with:
          app-name: ${{ inputs.webapp_name }}
          package: ${{ inputs.webapp_directory }}
          startup-command: "gunicorn --bind 0.0.0.0 --worker-class uvicorn.workers.UvicornWorker --timeout 600 app.main:app"
          # restart: true
