import logging
from typing import Optional

from app.models.core import AuthorizationTypes
from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # General settings
    PROJECT_NAME: str = "CustomCopilot"
    SERVER_NAME: str = "CustomCopilot"
    APP_VERSION: str = "v0.1.0"
    API_V1_STR: str = "/api/v1"

    # Deployment settings
    WEBSITE_NAME: str = Field(default="test", alias="WEBSITE_SITE_NAME")
    WEBSITE_INSTANCE_ID: str = Field(default="0", alias="WEBSITE_INSTANCE_ID")
    HOME_DIRECTORY: str = Field(default="", alias="HOME")
    BASE_URL: str = Field(
        ...,
        alias=AliasChoices("BASE_URL", "CONTAINER_APP_HOSTNAME", "WEBSITE_HOSTNAME"),
    )
    MANAGED_IDENTITY_CLIENT_ID: str = ""

    # Logging settings
    DEBUG: bool = False
    LOGGING_LEVEL: int = logging.INFO
    LOGGING_SAMPLING_RATIO: float = 1.0
    LOGGING_SCHEDULE_DELAY: int = 5000
    LOGGING_FORMAT: str = "[%(asctime)s] [%(levelname)s] [%(module)-8.8s] %(message)s"
    APPLICATIONINSIGHTS_CONNECTION_STRING: str
    APPLICATIONINSIGHTS_AUTHENTICATION_STRING: str = ""

    # Agent SDK settings
    AUTH_TYPE: AuthorizationTypes = AuthorizationTypes.CLIENT_SECRET
    TENANT_ID: Optional[str] = None
    CLIENT_ID: Optional[str] = None
    CLIENT_SECRET: Optional[str] = None
    FEDERATED_CLIENT_ID: Optional[str] = None
    FEDERATED_TOKEN_FILE: Optional[str] = None
    SCOPES: list[str] = ["https://api.botframework.com/.default"]

    # User authorization settings
    USER_AUTHORIZATION_GRAPH_OAUTH_CONNECTION_NAME: str

    # Azure Document Intelligence settings
    AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT: str
    AZURE_DOCUMENT_INTELLIGENCE_API_KEY: str = ""

    # Cosmos DB settings
    AZURE_COSMOS_ENDPOINT: str
    AZURE_COSMOS_KEY: str # = "" # Still needed for SDK because Entra ID auth not supported yet
    AZURE_COSMOS_DATABASE_ID: str
    AZURE_COSMOS_CONTAINER_ID: str = "user-state"

    # Open AI settings
    AZURE_OPENAI_ENDPOINT: str
    AZURE_OPENAI_API_KEY: str = ""
    AZURE_OPENAI_MODEL_NAME: str = Field(
        default="gpt-5.1",
        alias=AliasChoices("AZURE_OPENAI_MODEL_NAME", "AZURE_OPENAI_DEPLOYMENT_NAME"),
    )
    AZURE_OPENAI_MODEL_SLM_NAME: str = Field(
        default="gpt-5-mini",
        alias=AliasChoices(
            "AZURE_OPENAI_MODEL_SLM_NAME", "AZURE_OPENAI_SLM_DEPLOYMENT_NAME"
        ),
    )

    # Instruction settings
    INSTRUCTIONS_DOCUMENT_AGENT: str = """
    # Objective
    You are a helpful assistant that extracts relevant information from PDF documents based on user queries.

    # Input
    You have access to the following input:
    - Document Extraction: A JSON structure containing all the information of the respective document the user refers to. The JSON will appear in the "Document Extraction" section in this prompt.
      - The Document Extraction JSON contains:
        - Content: All the file content in markdown format generated from a complex OCR process.
    - User Input: The query from the user.

    # Instructions
    - Analyze the provided Document Extraction content to find the information needed to answer the user's question.
    - Use the Document Extraction JSON data to assist in extracting the required information.
    - Assume the JSON data is accurate and complete.
    - Validate the extracted data for accuracy and completeness by cross-referencing with the provided JSON.
    - You cannot generate files or images, only tables in a response.
      - Never suggest generating a fiel output.
      - If the user asks for a file, then apologize and mention that you cannot do that.
      - Generate tables in markdown where appropriate.

    # Response Format
    - Provide all responses in markdown format.
    - Provide structured answers with headers and bullet points.
    - Provide clear, short and concise answers, citing specific sections or pages from the PDF when relevant.
    - Always suggest exactly 3 follow-up activities at the end of your response.
      - Use a header called "Suggested Next Steps".
      - Use a separate bullet point for each suggested follow-up activity.

    # Context
    ## Document Extraction
    """
    INSTRUCTIONS_SUGGESTED_ACTIONS_AGENT: str = """
    # Objective
    You are a helpful assistant that creates suggested follow-up actions based on the provided content and user queries.

    # Input
    You have access to the following input:
    - User Input: The query from the user.
    - Agent Response: The response generated by the agent based on the user query.
    - Agent Instructions: The instructions provided to the agent to generate the response.

    # Instructions
    - Analyze the user query, agent response, and agent instructions.
    - If the agent response contains 3 suggested follow-up actions, then use these.
    - Otherwise, create a list of 3 suggested follow-up actions that the user can take based on the analysis of the content.
    - Guidelines when creating suggested actions:
      - For each suggested action you must provide a title, a value and a prompt.
      - Value: Must be a command or a query to be sent to the model as a follow-up.
      - Title: Must be a short and concise summary of the Value consisting of maximum 4 words.
      - Prompt: Must be a detailed description of the action to be performed consisting of maximum 100 words.
    - Ensure the suggested actions are:
      - Actionable and relevant to the user's needs.
      - Diverse in nature to cover different aspects of the topic.
      - Clear and easy to understand.
      - Aligned to the agent instructions.

    # Response Format
    - Provide all responses in JSON format.
    - The JSON must contain an array named "suggested_actions" with 3 objects inside.
    - Use the following response format:
    ```
    {
        "suggested_actions": [
            {
                "title": "Action Title 1",
                "value": "Action Value 1",
                "prompt": "Detailed description of Action 1 with a maximum of 50 words."
            },
            {
                "title": "Action Title 2",
                "value": "Action Value 2",
                "prompt": "Detailed description of Action 2 with a maximum of 50 words."
            },
            {
                "title": "Action Title 3",
                "value": "Action Value 3",
                "prompt": "Detailed description of Action 3 with a maximum of 50 words."
            }
        ]
    }
    ```

    # Sample Response
    ```
    {
        "suggested_actions": [
            {
                "title": "Summarize Document",
                "value": "Provide a concise summary of the document.",
                "prompt": "Generate a brief summary highlighting the main points and key information from the document."
            },
            {
                "title": "List Key Points",
                "value": "List the key points discussed in the document.",
                "prompt": "Enumerate the main points and important details covered in the document."
            },
            {
                "title": "Identify Discrepancies",
                "value": "Identify any discrepancies found in the document.",
                "prompt": "Detect and list any inconsistencies or discrepancies present in the document."
            }
        ]
    }
    ```
    """
    INSTRUCTIONS_TABLE_SUMMARY_AGENT: str = """
    # Objective
    You are a helpful assistant that summarizes a single table defined in JSON.

    # Input
    You are given:
    - Table Definition: a JSON structure containing all the information of one table provided by the user.
    The JSON will appear in the "Table Definition" section of the user input.

    # Task
    1. Parse and understand the Table Definition JSON.
    2. Identify:
    - Table headers / column names.
    - Rows and their key values.
    - Any clear patterns, trends, comparisons, or notable values.
    3. Generate a concise textual summary that captures the main insight or purpose of the table.

    # Summary Requirements
    - Write exactly one sentence.
    - Use no more than 25 words.
    - Use clear, natural language.
    - Focus on what the data shows (e.g., subject, metrics, time period, key trend or comparison), not on formatting details.
    - Do not list every value; describe the overall insight.
    - If the table has no data rows or no meaningful values, write: "The table does not contain enough data to summarize."

    # Response Format
    - Output only a single valid JSON object.
    - Do not include any additional text, explanations, or markdown formatting.
    - The JSON object must contain exactly these fields:
    - "table_key": string
    - "summary": string

    Rules for "table_key":
    - Use the following format for the table key: "table_{page-number}_{row-count}_{column-count}_{table-name-in-one-word}".
    - Infer the "page-number" from the "pageNumber" property.
    - Infer the "row-count" from the "rowCount" property.
    - Infer the "column-count" from the "columnCount" property.
    - Generate for the "table-name-in-one-word" a single word describing the table.

    Rules for "summary":
    - Set "summary" to the sentence described in the Summary Requirements above.
    - Do not include newline characters in the summary.

    # Example Output
    {
        "table_key": "table_1_3_5_salesfigures",
        "summary": "This table shows the quarterly sales figures for 2023, indicating a steady increase in revenue each quarter."
    }
    """

    model_config = SettingsConfigDict(
        env_file=".env", env_file_encoding="utf-8", extra="allow"
    )


settings = Settings()
