import logging
from typing import Optional

from app.models.core import AuthorizationTypes
from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # General settings
    PROJECT_NAME: str = "CustomCopilot"
    SERVER_NAME: str = "CustomCopilot"
    APP_VERSION: str = "v0.1.0"
    API_V1_STR: str = "/api/v1"

    # Deployment settings
    WEBSITE_NAME: str = Field(default="test", alias="WEBSITE_SITE_NAME")
    WEBSITE_INSTANCE_ID: str = Field(default="0", alias="WEBSITE_INSTANCE_ID")
    HOME_DIRECTORY: str = Field(default="", alias="HOME")
    BASE_URL: str = Field(
        ...,
        alias=AliasChoices("BASE_URL", "CONTAINER_APP_HOSTNAME", "WEBSITE_HOSTNAME"),
    )

    # Logging settings
    DEBUG: bool = False
    LOGGING_LEVEL: int = logging.INFO
    LOGGING_SAMPLING_RATIO: float = 1.0
    LOGGING_SCHEDULE_DELAY: int = 5000
    LOGGING_FORMAT: str = "[%(asctime)s] [%(levelname)s] [%(module)-8.8s] %(message)s"
    APPLICATIONINSIGHTS_CONNECTION_STRING: str = None

    # Agent SDK settings
    AUTH_TYPE: AuthorizationTypes = AuthorizationTypes.CLIENT_SECRET
    TENANT_ID: Optional[str] = None
    CLIENT_ID: Optional[str] = None
    CLIENT_SECRET: Optional[str] = None
    FEDERATED_CLIENT_ID: Optional[str] = None
    FEDERATED_TOKEN_FILE: Optional[str] = None
    SCOPES: list[str] = ["https://api.botframework.com/.default"]

    # Azure Document Intelligence settings
    AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT: str
    AZURE_DOCUMENT_INTELLIGENCE_API_KEY: str

    # Cosmos DB settings
    AZURE_COSMOS_ENDPOINT: str
    AZURE_COSMOS_KEY: str
    AZURE_COSMOS_DATABASE_ID: str
    AZURE_COSMOS_CONTAINER_ID: str = "user-state"

    # Open AI settings
    AZURE_OPENAI_ENDPOINT: str
    AZURE_OPENAI_API_KEY: str
    AZURE_OPENAI_MODEL_NAME: str = Field(
        default="gpt-5.1",
        alias=AliasChoices("AZURE_OPENAI_MODEL_NAME", "AZURE_OPENAI_DEPLOYMENT_NAME"),
    )
    AZURE_OPENAI_MODEL_SLM_NAME: str = Field(
        default="gpt-5-mini",
        alias=AliasChoices(
            "AZURE_OPENAI_MODEL_SLM_NAME", "AZURE_OPENAI_SLM_DEPLOYMENT_NAME"
        ),
    )

    # Instruction settings
    INSTRUCTIONS_DOCUMENT_AGENT: str = """
    # Objective
    You are a helpful assistant that extracts relevant information from PDF documents based on user queries.

    # Input
    You have access to the following input:
    - Document Extraction: A JSON structure containing all the information of the respective document the user refers to.

    # Instructions
    - Analyze the provided content to find the information needed to answer the user's question.
    - Use the JSON data to assist in extracting the required information.
    - Assume the JSON data is accurate and complete.
    - Validate the extracted data for accuracy and completeness by cross-referencing with the provided JSON.

    # Response Format
    - Provide all responses in markdown format.
    - Provide structured answers with headers and bullet points.
    - Provide clear, short and concise answers, citing specific sections or pages from the PDF when relevant.
    - Always suggest exactly 3 follow-up activities at the end.

    # Context

    ## Document Extraction
    """
    INSTRUCTIONS_SUGGESTED_ACTIONS_AGENT: str = """
    # Objective
    You are a helpful assistant that creates suggested follow-up actions based on the provided content and user queries.

    # Input
    You have access to the following input:
    - User Input: The query from the user.
    - Agent Response: The response generated by the agent based on the user query.
    - Agent Instructions: The instructions provided to the agent to generate the response.

    # Instructions
    - Analyze the user query, agent response, and agent instructions.
    - If the agent response contains 3 suggested follow-up actions, then use these.
    - Otherwise, create a list of 3 suggested follow-up actions that the user can take based on the analysis of the content.
    - Guidelines when creating suggested actions:
      - For each suggested action you must provide a title, a value and a prompt.
      - Value: Must be a command or a query to be sent to the model as a follow-up.
      - Title: Must be a short and concise summary of the Value consisting of maximum 4 words.
      - Prompt: Must be a detailed description of the action to be performed consisting of maximum 100 words.
    - Ensure the suggested actions are:
      - Actionable and relevant to the user's needs.
      - Diverse in nature to cover different aspects of the topic.
      - Clear and easy to understand.
      - Aligned to the agent instructions.

    # Response Format
    - Provide all responses in JSON format.
    - The JSON must contain an array named "suggested_actions" with 3 objects inside.
    - Use the following response format:
    ```
    {
        "suggested_actions": [
            {
                "title": "Action Title 1",
                "value": "Action Value 1",
                "prompt": "Detailed description of Action 1 with a maximum of 50 words."
            },
            {
                "title": "Action Title 2",
                "value": "Action Value 2",
                "prompt": "Detailed description of Action 2 with a maximum of 50 words."
            },
            {
                "title": "Action Title 3",
                "value": "Action Value 3",
                "prompt": "Detailed description of Action 3 with a maximum of 50 words."
            }
        ]
    }
    ```

    # Sample Response
    ```
    {
        "suggested_actions": [
            {
                "title": "Summarize Document",
                "value": "Provide a concise summary of the document.",
                "prompt": "Generate a brief summary highlighting the main points and key information from the document."
            },
            {
                "title": "List Key Points",
                "value": "List the key points discussed in the document.",
                "prompt": "Enumerate the main points and important details covered in the document."
            },
            {
                "title": "Identify Discrepancies",
                "value": "Identify any discrepancies found in the document.",
                "prompt": "Detect and list any inconsistencies or discrepancies present in the document."
            }
        ]
    }
    ```
    """

    model_config = SettingsConfigDict(
        env_file=".env", env_file_encoding="utf-8", extra="allow"
    )


settings = Settings()
